<a href="https://colab.research.google.com/github/khoa2210/Hoc-Python/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):

In [57]:
import numpy as np 

In [73]:
a = np.arange(7)
print(a)
print(np.ndim(a))
print(np.shape([a]))

[0 1 2 3 4 5 6]
1
(1, 7)


In [74]:
a = np.linspace(1,100,7,dtype = int)
print(a)
print(np.ndim(a))
np.shape([a])

[  1  17  34  50  67  83 100]
1


(1, 7)

In [75]:
a = np.logspace(0,1,num = 7, dtype  = int) 
print (a)
print(np.ndim(a))
np.shape([a])

[ 1  1  2  3  4  6 10]
1


(1, 7)

In [76]:
a = np.random.rand(1,7)
print(a)
print(np.ndim(a))
np.shape(a)

[[0.06855976 0.56766873 0.62490168 0.78719962 0.37706728 0.55620513
  0.34005469]]
2


(1, 7)

Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:

In [85]:
a = np.arange(70).reshape(10,7)
print(a)
print(np.ndim(a))
print(np.shape(a))

b = np.transpose(a)
print(b)
print(np.ndim(b))
print(np.shape(b))

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2
(10, 7)
[[ 0  7 14 21 28 35 42 49 56 63]
 [ 1  8 15 22 29 36 43 50 57 64]
 [ 2  9 16 23 30 37 44 51 58 65]
 [ 3 10 17 24 31 38 45 52 59 66]
 [ 4 11 18 25 32 39 46 53 60 67]
 [ 5 12 19 26 33 40 47 54 61 68]
 [ 6 13 20 27 34 41 48 55 62 69]]
2
(7, 10)


In [87]:
a = np.linspace(1,100,70,dtype = int).reshape(10,7)
print(a)
print(np.ndim(a))
print(np.shape(a))

b = np.transpose(a)
print(b)
print(np.ndim(b))
print(np.shape(b))

[[  1   2   3   5   6   8   9]
 [ 11  12  13  15  16  18  19]
 [ 21  22  23  25  26  28  29]
 [ 31  32  34  35  36  38  39]
 [ 41  42  44  45  46  48  49]
 [ 51  52  54  55  56  58  59]
 [ 61  62  64  65  67  68  69]
 [ 71  72  74  75  77  78  79]
 [ 81  82  84  85  87  88  89]
 [ 91  92  94  95  97  98 100]]
2
(10, 7)
[[  1  11  21  31  41  51  61  71  81  91]
 [  2  12  22  32  42  52  62  72  82  92]
 [  3  13  23  34  44  54  64  74  84  94]
 [  5  15  25  35  45  55  65  75  85  95]
 [  6  16  26  36  46  56  67  77  87  97]
 [  8  18  28  38  48  58  68  78  88  98]
 [  9  19  29  39  49  59  69  79  89 100]]
2
(7, 10)


In [93]:
a = np.logspace(0,2,num = 70, dtype  = int).reshape(10,7) 
print(a)
print(np.ndim(a))
print(np.shape(a))

b = np.transpose(a)
print(b)
print(np.ndim(b))
print(np.shape(b))

[[  1   1   1   1   1   1   1]
 [  1   1   1   1   2   2   2]
 [  2   2   2   3   3   3   3]
 [  4   4   4   4   5   5   6]
 [  6   6   7   7   8   9   9]
 [ 10  11  11  12  13  14  15]
 [ 16  17  18  20  21  23  24]
 [ 26  28  30  32  34  36  39]
 [ 41  44  47  51  54  58  62]
 [ 67  71  76  81  87  93 100]]
2
(10, 7)
[[  1   1   2   4   6  10  16  26  41  67]
 [  1   1   2   4   6  11  17  28  44  71]
 [  1   1   2   4   7  11  18  30  47  76]
 [  1   1   3   4   7  12  20  32  51  81]
 [  1   2   3   5   8  13  21  34  54  87]
 [  1   2   3   5   9  14  23  36  58  93]
 [  1   2   3   6   9  15  24  39  62 100]]
2
(7, 10)


In [95]:
a = np.random.rand(10,7)
print(a)
print(np.ndim(a))
print(np.shape(a))

b = np.transpose(a)
print(b)
print(np.ndim(b))
print(np.shape(b))

[[0.84245369 0.18478046 0.31390249 0.50094512 0.83825267 0.32819913
  0.33693854]
 [0.56541823 0.54154678 0.55887296 0.31591111 0.23824599 0.13336568
  0.48808488]
 [0.01381702 0.81770997 0.78891541 0.10750843 0.42313879 0.88527625
  0.66063885]
 [0.3103612  0.99658029 0.1663905  0.50204486 0.61764449 0.35793617
  0.04793838]
 [0.94478539 0.78548609 0.55296537 0.35243317 0.47013187 0.420169
  0.12045672]
 [0.0019115  0.64960505 0.20503869 0.38448187 0.3802067  0.70347659
  0.2875363 ]
 [0.26256553 0.86182997 0.69069848 0.20518447 0.91340138 0.44957253
  0.8613997 ]
 [0.58829493 0.43709163 0.13663897 0.64167225 0.13998784 0.11455577
  0.46763665]
 [0.40390434 0.68248104 0.30425936 0.53433712 0.95081711 0.64442094
  0.37088064]
 [0.53709141 0.30376674 0.20873833 0.74681306 0.96671814 0.09312864
  0.02152643]]
2
(10, 7)
[[0.84245369 0.56541823 0.01381702 0.3103612  0.94478539 0.0019115
  0.26256553 0.58829493 0.40390434 0.53709141]
 [0.18478046 0.54154678 0.81770997 0.99658029 0.78548609 

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [100]:
a = np.arange(70).reshape(10,7)
print(a.flatten())

b = np.reshape(a,(7,10))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [124]:
a = np.logspace(0,3,num = 150, dtype  = int).reshape(10,15) 
print(a)

print(a[3,])

print(a[:,5])

[[   1    1    1    1    1    1    1    1    1    1    1    1    1    1
     1]
 [   2    2    2    2    2    2    2    2    2    3    3    3    3    3
     3]
 [   4    4    4    4    4    5    5    5    5    6    6    6    7    7
     7]
 [   8    8    8    9    9   10   10   11   11   12   12   13   14   14
    15]
 [  16   16   17   18   19   20   21   22   23   24   25   26   28   29
    30]
 [  32   33   35   37   38   40   42   44   46   49   51   53   56   59
    61]
 [  64   67   71   74   78   81   85   89   94   98  103  108  113  118
   124]
 [ 130  136  142  149  156  163  171  179  188  197  206  216  226  237
   248]
 [ 260  273  286  299  313  328  344  360  377  395  414  434  454  476
   498]
 [ 522  547  573  600  629  658  690  722  757  793  830  870  911  954
  1000]]
[ 8  8  8  9  9 10 10 11 11 12 12 13 14 14 15]
[  1   2   5  10  20  40  81 163 328 658]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [141]:
array = np.random.randint(10, size=(15, 10))
print(array)

[[3 3 6 5 9 5 4 2 8 8]
 [9 3 1 3 2 6 5 0 1 2]
 [7 4 4 6 9 9 9 9 0 3]
 [6 9 0 5 4 2 3 9 7 0]
 [7 7 8 2 9 4 4 5 9 0]
 [8 3 5 4 2 8 9 8 6 9]
 [6 5 9 5 0 9 6 8 2 4]
 [9 1 3 7 9 0 7 9 3 0]
 [5 8 1 3 4 9 0 5 2 0]
 [0 0 5 2 9 3 8 5 9 8]
 [2 4 1 2 9 8 6 0 0 9]
 [4 9 1 8 7 5 2 9 2 9]
 [0 8 6 4 3 6 4 6 8 8]
 [1 1 0 8 4 0 3 9 2 3]
 [9 5 1 3 6 4 9 0 9 4]]


In [145]:
import statistics as sta
from scipy import stats

def trungbinh(vector_a):
    return np.average(vector_a)

def trungvi(vector_a):
    return np.median(vector_a)

def phuongsai(vector_a):
    return sta.variance(vector_a)

def dolechchuan(vector_a):
    return sta.stdev(vector_a)

def yeuvi(vector_a):
    return stats.mode(vector_a)

In [160]:
print("Giá trị trung bình : \n", np.apply_along_axis(trungbinh, 1, array))

Giá trị trung bình : 
 [5.3 3.2 6.  4.5 5.5 6.2 5.4 4.8 3.7 4.9 4.1 5.6 5.3 3.1 5. ]


In [161]:
print("Giá trị phương sai : \n", np.apply_along_axis(phuongsai, 1, array))

Giá trị phương sai : 
 [ 5  7 10 10  9  6  8 14  9 12 13 10  6  9 10]


In [162]:
print("Giá trị trung vị : \n", np.apply_along_axis(trungvi, 1, array))

Giá trị trung vị : 
 [5.  2.5 6.5 4.5 6.  7.  5.5 5.  3.5 5.  3.  6.  6.  2.5 4.5]


In [163]:
print("Giá trị độ lệch chuẩn : \n", np.apply_along_axis(dolechchuan, 1, array))

Giá trị độ lệch chuẩn : 
 [2.23606798 2.64575131 3.16227766 3.16227766 3.         2.44948974
 2.82842712 3.74165739 3.         3.46410162 3.60555128 3.16227766
 2.44948974 3.         3.16227766]


In [164]:
print("Giá trị yếu vị : \n", np.apply_along_axis(yeuvi, 1, array))

Giá trị yếu vị : 
 [[[3]
  [2]]

 [[1]
  [2]]

 [[9]
  [4]]

 [[0]
  [2]]

 [[4]
  [2]]

 [[8]
  [3]]

 [[5]
  [2]]

 [[9]
  [3]]

 [[0]
  [2]]

 [[0]
  [2]]

 [[0]
  [2]]

 [[9]
  [3]]

 [[6]
  [3]]

 [[0]
  [2]]

 [[9]
  [3]]]


In [170]:
print("Giá trị trung bình : \n", np.apply_along_axis(trungbinh, 0, array))

Giá trị trung bình : 
 [5.06666667 4.66666667 3.4        4.46666667 5.73333333 5.2
 5.26666667 5.6        4.53333333 4.46666667]


In [169]:
print("Giá trị phương sai : \n", np.apply_along_axis(phuongsai, 0, array))

Giá trị phương sai : 
 [10  8  8  4 10  9  7 12 12 13]


In [168]:
print("Giá trị trung vị : \n", np.apply_along_axis(trungvi, 0, array))

Giá trị trung vị : 
 [6. 4. 3. 4. 6. 5. 5. 6. 3. 4.]


In [166]:
print("Giá trị độ lệch chuẩn : \n", np.apply_along_axis(dolechchuan, 0, array))

Giá trị độ lệch chuẩn : 
 [3.16227766 2.82842712 2.82842712 2.         3.16227766 3.
 2.64575131 3.46410162 3.46410162 3.60555128]


In [165]:
print("Giá trị yếu vị : \n", np.apply_along_axis(yeuvi, 0, array))

Giá trị yếu vị : 
 [[[9 3 1 2 9 9 4 9 2 0]]

 [[3 3 5 3 6 3 3 5 4 4]]]
