<a href="https://colab.research.google.com/github/khoa2210/Hoc-Python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3 , một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [2]:
import numpy as np


In [76]:
a = np.array([5,7,14])
print(a)

[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7,
8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [77]:
a = np.arange(1,16)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: 

In [61]:
num = int(input("Nhập 1 số dương : "))
# Vecto hàng
a = np.array(np.random.random(num))
# Vecto cột
b = np.transpose([np.random.random(num)])
print(a)
print(b)

Nhập 1 số dương : 3
[0.27630267 0.77862697 0.46239646]
[[0.09893788]
 [0.01014594]
 [0.72239064]]


Bài 4

In [47]:
import numpy as np

v = np.transpose([np.array([7,-5,8])])
# Chiều dài vector
magnitude = np.linalg.norm(v)
print(magnitude)

11.74734012447073


Bài 5:

In [60]:
a = np.random.random(2)
b = np.random.random(2)
# Vector AB
v = np.array(b - a)
print(v)
# Chiều dài vector
magnitude = np.linalg.norm(v)
print(magnitude)

[ 0.8561451  -0.41259073]
0.9503765280054975


Bài 6:

In [64]:
num = int(input("Nhập 1 số dương : "))
a = np.array(np.random.random(num))
b = np.array(np.random.random(num))
np.inner(a, b)

Nhập 1 số dương : 3


0.998269358663775

Bài 7 

In [66]:
num = int(input("Nhập 1 số dương : "))
a = np.array(np.random.random(num))
b = np.array(np.random.random(num))
np.cross(a,b)

Nhập 1 số dương : 3


array([-0.13110071,  0.16846375,  0.15807733])

Bài 8

In [70]:
num = int(input("Nhập 1 số dương : "))
a = np.array([np.random.random(num)])
b = np.transpose(a)
print(a)
print(b)

Nhập 1 số dương : 3
[[0.46917588 0.65671935 0.33356154]]
[[0.46917588]
 [0.65671935]
 [0.33356154]]


Bài 9 

In [72]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [73]:
b = [[1], [2], [3], [4], [5]]
print(b)

[[1], [2], [3], [4], [5]]


In [81]:
c = np.array([[1,2,3,4,5]])
print(c)

[[1 2 3 4 5]]


In [88]:
d = np.transpose(c)
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [89]:
e = np.array([[1],[2],[3],[4],[5]])
print(e)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [90]:
f = np.transpose(e)
print(f)

[[1 2 3 4 5]]


Bài 10

In [91]:
num = int(input("Nhập 1 số dương : "))
a = np.array([np.random.random(num)])
b = np.array([np.random.random(num)])

Nhập 1 số dương : 3


In [92]:
# Nhân vector
print(a*3)

[[1.5166624  2.76168156 2.39469887]]


In [93]:
# Cộng 2 vector
print(a + b)

[[0.56627038 0.93374026 0.961363  ]]
