<a href="https://colab.research.google.com/github/khoa2210/Hoc-Python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1 :Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5 , giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [2]:
import numpy as np

In [25]:
array = np.random.randint(100, size=(7, 5))
print(array)

[[78 94 83 52  9]
 [76 14  8 44 66]
 [31 10 64  7 99]
 [45  7 82 62 43]
 [17 35 33 56 49]
 [ 5 67 78  9 48]
 [84 88 94 61 42]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [26]:
array1 = np.zeros((6,7))
print(array1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ R7×7

, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả

xuất ra màn hình.

In [27]:
array2 = np.random.randint(100, size=(7, 7))
print(array2)

[[70 48 15 89 23  9 67]
 [ 4  6 31 58 46 86 92]
 [51 62 26 92 73 77 91]
 [64 95 58  9 95 12 99]
 [97 29 15 34 99 84 48]
 [68 91 65 28 13 88 56]
 [48 26  0 85 53 70 34]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá
trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra
màn hình.

In [28]:
a = np.zeros((6, 6), int)
np.fill_diagonal(a, 15)
print(a)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm
numpy.triu(). Kết quả xuất ra màn hình.

In [29]:
array3 = np.random.randint(100, size=(8, 8))
array3 = np.triu(array3,1)
print(array3)

[[ 0 23 77 43 44 78 55 61]
 [ 0  0 85 20 68 60 79 10]
 [ 0  0  0 26 68 36 35 31]
 [ 0  0  0  0 92 26 41 75]
 [ 0  0  0  0  0 20  1 53]
 [ 0  0  0  0  0  0 38  6]
 [ 0  0  0  0  0  0  0 30]
 [ 0  0  0  0  0  0  0  0]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [33]:
array4 = np.random.randint(100, size=(8, 8))
array4 = np.tril(array4,-1)
print(array4)

[[ 0  0  0  0  0  0  0  0]
 [94  0  0  0  0  0  0  0]
 [69 53  0  0  0  0  0  0]
 [79 85 30  0  0  0  0  0]
 [12 81 40 70  0  0  0  0]
 [98 56 28 63 16  0  0  0]
 [80 97 54 38 85 13  0  0]
 [86 54 57 49 16  5 93  0]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [34]:
array5 = np.eye(9)
print(array5)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 

Phép cộng ma trận: Am×n + Bm×n = Cm×n. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

In [35]:
array6 = np.random.randint(100, size=(6, 7))
array7 = np.random.randint(100, size=(6, 7))
print(array6 + array7)

[[148  62  79  96 117 132  66]
 [166  95  69 114  50 109 151]
 [ 44 108 119  84 167 119 133]
 [ 91 103  66 117  80 178  95]
 [ 55 133 120  23  65 108  79]
 [ 74 154  12  59  90  71 146]]


Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước
5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất
ra màn hình.

In [38]:
a = int(input("Nhập số "))
array8 = np.random.randint(100, size=(5, 8))
print(np.dot(a,array8))

Nhập số 4
[[ 68   8 172 308 212 196 200  48]
 [176 340 196  16 356 332 220 336]
 [116 240 380 316 384 312  80 252]
 [396 116 100 276  76 192 100 296]
 [352 128   0 196 144  44 276 244]]


Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

In [41]:
array9 = np.random.randint(100, size=(3, 7))
array10 = np.transpose(array9)
print(array10)

[[ 5 71 74]
 [35  0 38]
 [39  5  5]
 [38 27 63]
 [15 82 67]
 [41 17 73]
 [11 24 94]]


Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()

In [42]:
array11 = np.random.randint(100, size=(5, 7))
array12 = np.random.randint(100, size=(7, 3))
print(np.dot(array11,array12))

[[18753 20313 13645]
 [21820 22200 17426]
 [20143 13425 16028]
 [11839 10333 10684]
 [13366 11851  7541]]


Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi

ý: sử dụng hàm numpy.linalg.inv()

In [45]:
A = np.random.randint(100, size=(5, 5))
print(np.linalg.inv(A))

[[-0.0234625   0.0051088   0.03551484 -0.0056193   0.00212399]
 [ 0.02641033 -0.01353032 -0.02500923  0.00981829 -0.00214386]
 [ 0.00463823  0.01339886 -0.00569264  0.00546464 -0.01960616]
 [ 0.0305481  -0.01092416 -0.05954099  0.02821442  0.00800517]
 [-0.01275153  0.00511758  0.02144855 -0.0194458   0.01893046]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau
 Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
 Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [47]:
array13 = np.random.randint(100, size=(1, 8))
array14 = np.random.randint(100, size=(8, 1))
print(array13)
print(array14)

[[15 66 27 59 67 64 44 54]]
[[65]
 [82]
 [98]
 [ 8]
 [76]
 [22]
 [25]
 [35]]


Bài 10 - Hệ phương trình tuyến tính: ví dụ ta có phương trình

2x-2y+z=-3

x+3y-2z=1

3x-y-z=2

In [52]:
# đưa hệ phương trình về ma trận 
a = np.array([[2,-2,1],[1,3,-2],[3,-1,-1]])
print(a)
b = np.array([-3,1,2])

[[ 2 -2  1]
 [ 1  3 -2]
 [ 3 -1 -1]]


In [55]:
print(np.linalg.solve(a,b))

[-1.4 -2.  -4.2]


Khi đó x = -1,4, y=-2, z= -4,2