<a href="https://colab.research.google.com/github/khoa2210/Hoc-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Khai báo thư viện Numpy

In [1]:
import numpy as np 

Khởi tạo mảng 1 chiều 

In [2]:
#Khởi tạo mảng một chiều 
arr = np.array([1,2,3,4,5,6], dtype = int)

#Khởi tạo mảng một chiều với kiểu dữ liệu mặc định
arr = np.array([1,2,3,4,5,6])

print(arr)

[1 3 4 5 6]


Mảng đa chiều (ma trận)

In [4]:
arr1 = np.array([(4,5,6), (1,2,3),(7,8,9)], dtype = int)

print(arr1)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


Truy cập phần tử của ma trận


In [10]:
print(arr1[0,0])

4


Tính kích thước ma trận

In [11]:
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(arr2.shape)

(3, 4)


Các phép toán ma trận 

In [13]:
# Cộng trừ 2 ma trận 
A = np.array([[1, 3, 4], [-2, 6, 0], [-5, 7, 2]])
B = np.array([[2, 3, 4], [-1, -2, -3], [0, 4, -4]])
print(A + B)
print(A - B)

[[ 3  6  8]
 [-3  4 -3]
 [-5 11 -2]]
[[-1  0  0]
 [-1  8  3]
 [-5  3  6]]


Nhân chia ma trận với 1 số 

In [14]:
print(A*3)
print(B/2)

[[  3   9  12]
 [ -6  18   0]
 [-15  21   6]]
[[ 1.   1.5  2. ]
 [-0.5 -1.  -1.5]
 [ 0.   2.  -2. ]]


Nhân 2 ma trận với nhau

In [15]:
print(A @ B)
print(B @ A)

[[ -1  13 -21]
 [-10 -18 -26]
 [-17 -21 -49]]
[[-24  52  16]
 [ 18 -36 -10]
 [ 12  -4  -8]]


Ma trận đơn vị 

In [16]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Ma trận đường chéo

In [17]:
A = np.diag([1, 2, 3])
print(A)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


Ma trận chuyển vị

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(np.transpose(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Ma trận vuông

In [20]:
A = np.array([[2, 1, 3], [5, 3, 2], [1, 4, 3]])
print(np.linalg.det(A))

40.000000000000014


Ma trận nghịch đảo 

In [21]:
A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
print(np.linalg.inv(A))

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]
