<a href="https://colab.research.google.com/github/khoa2210/Hoc-Python/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

Cú pháp:

numpy.apply_along_axis(1d_func, axis, array, *args, **kwargs) 
 
Trong đó 

1d_func: hàm bắt buộc để thực hiện trên mảng.

axis: trục  dọc

array: mảng đầu vào

*args: Các đối số bổ sung cho chức năng 

** kwargs: Các đối số bổ sung cho chức năng  

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
import numpy as np

In [ ]:
array = np.random.randint(100, size=(15, 17))
print(array)

[[13 45 54 23 18 16 21 18 64 37 92 32 63 46 18 26 31]
 [30 10 70 39 47 26 45  5 66 97 69  4 17 85 98 36 73]
 [74 61  4 93  3 96 55 15  4 69 99 86 54 99 10 10 46]
 [70 36 83 28 98 64 38 40 18 29 22 42 97 47 52 15  8]
 [ 8 76 88  3 82  0 97 47 54 67 33 14 92 43 40 90 27]
 [80  8  0 71 52 59 31 26 15  6 36 12 14 92 24 69  3]
 [65 55 61 78 23 22 45 57 67 63  7 14 66 95 23 74 55]
 [86 99 77  3 78 51 13 79 69 53 85 89 61  7 33 85 79]
 [50 52 22 94 29 94 59 51 19 17 65  1  8 21 94 56 32]
 [32 54 46 92 51 87 17  9 45 43 16 99 92 13 27 85 47]
 [74 32 54 16 30  2 27 11 92 44 23 51 79 41 56 88 32]
 [76 98  7 66 29 25 88 95 61 65 67 23 92 29 36 69 17]
 [37  4 50 63 74 31 96 65 39 50  4 11 63 53 14 89 89]
 [50 17 61  2 14 20  1 67 89 20 72 26  5 86  5 80 45]
 [51 81 57 28 78 99 47 99 89 74 43 43 22 20 36 26 68]]


Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [26]:
def tim_gia_tri_lon_nhat(vector_a):
    return np.max(vector_a)

In [28]:
print("Giá trị lớn nhất : \n", np.apply_along_axis(tim_gia_tri_lon_nhat, 1, array))

Giá trị lớn nhất : 
 [92 98 99 98 97 92 95 99 94 99 92 98 96 89 99]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [29]:
def tim_gia_tri_nho_nhat(vector_a):
    return np.min(vector_a)

In [30]:
print("Giá trị nhỏ nhất : \n", np.apply_along_axis(tim_gia_tri_nho_nhat, 0, array))

Giá trị nhỏ nhất : 
 [ 8  4  0  2  3  0  1  5  4  6  4  1  5  7  5 10  3]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [31]:
def tinh_tong(vector_a):
    return np.sum(vector_a)

In [32]:
print("Giá trị tổng : \n", np.apply_along_axis(tinh_tong, 1, array))

Giá trị tổng : 
 [ 617  817  878  787  861  598  870 1047  764  855  752  943  832  660
  961]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [87]:
def tinh_tong1(vector_a):
  return sum(n for n in vector_a if n % 2 != 0)

In [88]:
print("Giá trị tổng : \n", np.apply_along_axis(tinh_tong1, 1, array))

Giá trị tổng : 
 [233 477 494 271 317 248 616 883 262 523 232 487 540 290 609]
